FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps ./apps
RUN npm ci
RUN npm run build

FROM nginx:1.27-alpine
COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/widget/dist /usr/share/nginx/html/widget
COPY --from=build /app/apps/admin/dist /usr/share/nginx/html/admin
EXPOSE 80
